env:
  browser: true
  es2021: true
  node: true
extends:
  - google
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  'quotes': [ 'error', 'single' ],
  'semi': [ 'error', 'always' ],
  'indent': [ 'error', 4 ],
  'no-multi-spaces': [ 'error' ],
  'require-jsdoc' : 0,
  'max-len': ['error', 140],
}
