on:
  push:

jobs:
  test:
    name: E2E Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.19.0

      - name: Install dependencies
        run: npm install

      - name: Run e2e tests
        run: npm run test